name: build-and-cache

on:
  workflow_call:
    secrets:
      CACHIX_AUTH_TOKEN:
        required: true
      CACHIX_SIGNING_KEY:
        required: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - system: aarch64-darwin
            runner: macos-latest
          - system: x86_64-linux
            runner: ubuntu-latest
    runs-on: ${{ matrix.runner }}
    environment: Build
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main

      - uses: cachix/cachix-action@v15
        with:
          name: nhatanh-h2
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"

      - name: Build every shell for this system
        run: |
          attrs="goShell rustShells.stable rustShells.nightly"
          for name in $(echo "$attrs"); do
            echo "::group::Building $name"
            nix build --accept-flake-config ".#devShells.${{ matrix.system }}.$name" -L
            echo "::endgroup::"
          done
